### ISSUE TITLE
Logging for RaspberryPi controller python code

### ISSUE THREAD

**Issue by fergusL** [AstroHuntsman/huntsman-dome#21]
Need some form of logging for the RaspberryPi/automationHAT

**Comment by lspitler** [comment]
We do. I wonder how we send a serious fault (e.g. movement command doesn't change the encoder) to POCS? Any thoughts or suggestions @wtgee or @AnthonyHorton ?

**Comment by AnthonyHorton** [comment]
Communications would normally go via TheSkyX, I think. When TheSkyX calls a method of the dome driver it can, and should, return an error code if something goes wrong. POCS should, in turn, be getting info on the dome status from TheSkyX. We can go around TheSkyX and have POCS and the dome controller talking directly to each other if we really have to, but that would be a new interface to design and implement.

As for logging, yes, lots of it. Here we should follow the approach of POCS/huntsman-pocs.  We can use code from `panoptes-utils`, https://github.com/panoptes/panoptes-utils/blob/develop/panoptes/utils/logger.py

**Comment by wtgee** [comment]
@fergusL has any work started on the logging? I started to add a bunch as I was installing it here just because I needed to see what was going on. I'm about to clean that up and submit a PR but didn't want to overlap with any potential work.

You mentioned to me that you were thinking of using [LogBook](https://logbook.readthedocs.io/en/stable/), which I think is a good choice, but that is not what I have done so far. Could probably easily be converted. 

I'll probably submit this PR soon anyway, but if you have a branch with some work on it please let me know.
